"""cloud baseline

Revision ID: 20260903_0001
Revises:
Create Date: 2026-09-03 22:34:43.800835
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260903_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "children",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("grade", sa.String(length=20), nullable=True),
        sa.Column("daily_budget_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_children_family_id"), "children", ["family_id"], unique=False)
    op.create_table(
        "wechat_actor_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("app_id", sa.String(length=32), nullable=False),
        sa.Column("subject_hmac", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id", "subject_hmac", name="uq_wechat_actor_subject"),
    )
    op.create_index(
        op.f("ix_wechat_actor_bindings_family_id"),
        "wechat_actor_bindings",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wechat_actor_bindings_status"), "wechat_actor_bindings", ["status"], unique=False
    )
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("repeat_weekly", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_events_child_id"), "calendar_events", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_event_date"), "calendar_events", ["event_date"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_family_id"), "calendar_events", ["family_id"], unique=False
    )
    op.create_table(
        "learning_submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("proposal_json", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_submissions_child_id"), "learning_submissions", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_submissions_family_id"),
        "learning_submissions",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_submissions_state"), "learning_submissions", ["state"], unique=False
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "child_id", "name", name="uq_subject_name"),
    )
    op.create_index(op.f("ix_subjects_child_id"), "subjects", ["child_id"], unique=False)
    op.create_index(op.f("ix_subjects_family_id"), "subjects", ["family_id"], unique=False)
    op.create_table(
        "activity_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_records_child_id"), "activity_records", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_records_family_id"), "activity_records", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_records_occurred_at"), "activity_records", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_activity_records_subject_id"), "activity_records", ["subject_id"], unique=False
    )
    op.create_table(
        "activity_schedules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("weekdays", sa.String(length=30), nullable=False),
        sa.Column("time_text", sa.String(length=20), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("target_per_week", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_schedules_child_id"), "activity_schedules", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_schedules_family_id"), "activity_schedules", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_schedules_subject_id"), "activity_schedules", ["subject_id"], unique=False
    )
    op.create_table(
        "agent_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["learning_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", name="uq_job_submission"),
    )
    op.create_index(op.f("ix_agent_jobs_family_id"), "agent_jobs", ["family_id"], unique=False)
    op.create_index(op.f("ix_agent_jobs_state"), "agent_jobs", ["state"], unique=False)
    op.create_table(
        "calendar_event_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["calendar_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "idempotency_key", name="uq_calendar_event_request_key"),
    )
    op.create_index(
        op.f("ix_calendar_event_requests_event_id"),
        "calendar_event_requests",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_event_requests_family_id"),
        "calendar_event_requests",
        ["family_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("normalized_name", sa.String(length=140), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("review_method", sa.String(length=60), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "family_id",
            "child_id",
            "subject_id",
            "normalized_name",
            "category",
            name="uq_knowledge_identity",
        ),
    )
    op.create_index(
        op.f("ix_knowledge_items_child_id"), "knowledge_items", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_items_family_id"), "knowledge_items", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_items_subject_id"), "knowledge_items", ["subject_id"], unique=False
    )
    op.create_table(
        "learning_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["learning_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id"),
    )
    op.create_index(
        op.f("ix_learning_records_child_id"), "learning_records", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_records_family_id"), "learning_records", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_records_occurred_at"), "learning_records", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_learning_records_subject_id"), "learning_records", ["subject_id"], unique=False
    )
    op.create_table(
        "media_objects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("backend", sa.String(length=30), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("storage_ref", sa.String(length=700), nullable=True),
        sa.Column("uploader_subject_hmac", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["learning_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "idempotency_key", name="uq_media_ticket_request"),
        sa.UniqueConstraint("storage_path", name="uq_media_storage_path"),
        sa.UniqueConstraint("storage_ref", name="uq_media_storage_ref"),
    )
    op.create_index(
        op.f("ix_media_objects_expires_at"), "media_objects", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_media_objects_family_id"), "media_objects", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_media_objects_state"), "media_objects", ["state"], unique=False)
    op.create_index(
        op.f("ix_media_objects_submission_id"), "media_objects", ["submission_id"], unique=False
    )
    op.create_table(
        "submission_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["learning_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "idempotency_key", name="uq_submission_request_key"),
        sa.UniqueConstraint("submission_id", name="uq_submission_request_submission"),
    )
    op.create_index(
        op.f("ix_submission_requests_family_id"), "submission_requests", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_submission_requests_submission_id"),
        "submission_requests",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_occurrences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("knowledge_item_id", sa.String(length=36), nullable=False),
        sa.Column("learning_record_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_item_id"],
            ["knowledge_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["learning_record_id"],
            ["learning_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_occurrences_family_id"),
        "knowledge_occurrences",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_occurrences_knowledge_item_id"),
        "knowledge_occurrences",
        ["knowledge_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_occurrences_learning_record_id"),
        "knowledge_occurrences",
        ["learning_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_occurrences_occurred_at"),
        "knowledge_occurrences",
        ["occurred_at"],
        unique=False,
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_item_id", sa.String(length=36), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("last_feedback", sa.String(length=30), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_item_id"],
            ["knowledge_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("knowledge_item_id", name="uq_review_knowledge"),
    )
    op.create_index(op.f("ix_review_items_child_id"), "review_items", ["child_id"], unique=False)
    op.create_index(op.f("ix_review_items_due_date"), "review_items", ["due_date"], unique=False)
    op.create_index(op.f("ix_review_items_family_id"), "review_items", ["family_id"], unique=False)
    op.create_table(
        "submission_media",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("media_object_id", sa.String(length=36), nullable=True),
        sa.Column("path", sa.String(length=700), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_object_id"],
            ["media_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["learning_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_media_media_object_id"),
        "submission_media",
        ["media_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submission_media_submission_id"),
        "submission_media",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "review_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("review_item_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_item_id"],
            ["review_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_feedback_family_id"), "review_feedback", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_feedback_review_item_id"),
        "review_feedback",
        ["review_item_id"],
        unique=False,
    )
    op.create_table(
        "review_feedback_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("review_item_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("result_step", sa.Integer(), nullable=False),
        sa.Column("result_due_date", sa.Date(), nullable=False),
        sa.Column("result_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_item_id"],
            ["review_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "idempotency_key", name="uq_review_feedback_request_key"),
    )
    op.create_index(
        op.f("ix_review_feedback_requests_family_id"),
        "review_feedback_requests",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_feedback_requests_review_item_id"),
        "review_feedback_requests",
        ["review_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_review_feedback_requests_review_item_id"), table_name="review_feedback_requests"
    )
    op.drop_index(
        op.f("ix_review_feedback_requests_family_id"), table_name="review_feedback_requests"
    )
    op.drop_table("review_feedback_requests")
    op.drop_index(op.f("ix_review_feedback_review_item_id"), table_name="review_feedback")
    op.drop_index(op.f("ix_review_feedback_family_id"), table_name="review_feedback")
    op.drop_table("review_feedback")
    op.drop_index(op.f("ix_submission_media_submission_id"), table_name="submission_media")
    op.drop_index(op.f("ix_submission_media_media_object_id"), table_name="submission_media")
    op.drop_table("submission_media")
    op.drop_index(op.f("ix_review_items_family_id"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_due_date"), table_name="review_items")
    op.drop_index(op.f("ix_review_items_child_id"), table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(op.f("ix_knowledge_occurrences_occurred_at"), table_name="knowledge_occurrences")
    op.drop_index(
        op.f("ix_knowledge_occurrences_learning_record_id"), table_name="knowledge_occurrences"
    )
    op.drop_index(
        op.f("ix_knowledge_occurrences_knowledge_item_id"), table_name="knowledge_occurrences"
    )
    op.drop_index(op.f("ix_knowledge_occurrences_family_id"), table_name="knowledge_occurrences")
    op.drop_table("knowledge_occurrences")
    op.drop_index(op.f("ix_submission_requests_submission_id"), table_name="submission_requests")
    op.drop_index(op.f("ix_submission_requests_family_id"), table_name="submission_requests")
    op.drop_table("submission_requests")
    op.drop_index(op.f("ix_media_objects_submission_id"), table_name="media_objects")
    op.drop_index(op.f("ix_media_objects_state"), table_name="media_objects")
    op.drop_index(op.f("ix_media_objects_family_id"), table_name="media_objects")
    op.drop_index(op.f("ix_media_objects_expires_at"), table_name="media_objects")
    op.drop_table("media_objects")
    op.drop_index(op.f("ix_learning_records_subject_id"), table_name="learning_records")
    op.drop_index(op.f("ix_learning_records_occurred_at"), table_name="learning_records")
    op.drop_index(op.f("ix_learning_records_family_id"), table_name="learning_records")
    op.drop_index(op.f("ix_learning_records_child_id"), table_name="learning_records")
    op.drop_table("learning_records")
    op.drop_index(op.f("ix_knowledge_items_subject_id"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_family_id"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_child_id"), table_name="knowledge_items")
    op.drop_table("knowledge_items")
    op.drop_index(
        op.f("ix_calendar_event_requests_family_id"), table_name="calendar_event_requests"
    )
    op.drop_index(op.f("ix_calendar_event_requests_event_id"), table_name="calendar_event_requests")
    op.drop_table("calendar_event_requests")
    op.drop_index(op.f("ix_agent_jobs_state"), table_name="agent_jobs")
    op.drop_index(op.f("ix_agent_jobs_family_id"), table_name="agent_jobs")
    op.drop_table("agent_jobs")
    op.drop_index(op.f("ix_activity_schedules_subject_id"), table_name="activity_schedules")
    op.drop_index(op.f("ix_activity_schedules_family_id"), table_name="activity_schedules")
    op.drop_index(op.f("ix_activity_schedules_child_id"), table_name="activity_schedules")
    op.drop_table("activity_schedules")
    op.drop_index(op.f("ix_activity_records_subject_id"), table_name="activity_records")
    op.drop_index(op.f("ix_activity_records_occurred_at"), table_name="activity_records")
    op.drop_index(op.f("ix_activity_records_family_id"), table_name="activity_records")
    op.drop_index(op.f("ix_activity_records_child_id"), table_name="activity_records")
    op.drop_table("activity_records")
    op.drop_index(op.f("ix_subjects_family_id"), table_name="subjects")
    op.drop_index(op.f("ix_subjects_child_id"), table_name="subjects")
    op.drop_table("subjects")
    op.drop_index(op.f("ix_learning_submissions_state"), table_name="learning_submissions")
    op.drop_index(op.f("ix_learning_submissions_family_id"), table_name="learning_submissions")
    op.drop_index(op.f("ix_learning_submissions_child_id"), table_name="learning_submissions")
    op.drop_table("learning_submissions")
    op.drop_index(op.f("ix_calendar_events_family_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_event_date"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_child_id"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_wechat_actor_bindings_status"), table_name="wechat_actor_bindings")
    op.drop_index(op.f("ix_wechat_actor_bindings_family_id"), table_name="wechat_actor_bindings")
    op.drop_table("wechat_actor_bindings")
    op.drop_index(op.f("ix_children_family_id"), table_name="children")
    op.drop_table("children")
    # ### end Alembic commands ###
