"""Operator helper for the two notification values that cannot live in the repository.

`PUSH_KIDS_NOTIFICATION_SECRET_KEY` is generated by the deployment (it protects stored WeChat
OpenIDs), while `PUSH_KIDS_NOTIFICATION_TEMPLATES` mirrors templates approved in the WeChat console.
This tool only generates and validates those values locally; it never contacts WeChat and never
prints an existing secret.
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps" / "api" / "src"))

from push_kids.notifications.domain import KINDS  # noqa: E402
from push_kids.notifications.templates import ALLOWED_SEMANTICS, parse_templates  # noqa: E402

# Semantics each type can actually fill, so the operator maps WeChat fields to real content.
USED_SEMANTICS: dict[str, tuple[str, ...]] = {
    "member_application": ("headline", "detail", "code"),
    "schedule_reminder": ("headline", "child", "time", "detail"),
    "review_digest": ("headline", "detail"),
}
# A plausible WeChat field key per semantic, used only for the scaffold skeleton.
SAMPLE_FIELD: dict[str, str] = {
    "headline": "thing1",
    "detail": "thing2",
    "child": "name3",
    "time": "time4",
    "code": "character_string5",
}


def cmd_secret(_: argparse.Namespace) -> int:
    """Print one fresh key: generated here, pasted into the runtime config, never committed."""
    print(secrets.token_urlsafe(32))
    print(
        "把它填到微信云托管服务的环境变量 PUSH_KIDS_NOTIFICATION_SECRET_KEY，不要写进仓库或聊天。",
        file=sys.stderr,
    )
    print(
        "轮换这个值会让已保存的微信接收信息无法解密，家长需要重新在小程序里开启提醒。",
        file=sys.stderr,
    )
    return 0


def cmd_scaffold(_: argparse.Namespace) -> int:
    """Print a template skeleton to fill with ids and field keys from the WeChat console."""
    skeleton = {
        kind.type: {
            "template_id": f"<{kind.type}_模板ID>",
            "fields": {SAMPLE_FIELD[semantic]: semantic for semantic in USED_SEMANTICS[kind.type]},
            "long_term": False,
        }
        for kind in KINDS
    }
    print(json.dumps(skeleton, ensure_ascii=False, indent=2))
    notes = [
        "",
        "模板 ID 与 fields 的键来自微信公众平台后台：",
        "  小程序管理后台 → 功能 → 订阅消息 → 我的模板（选用公共模板库并记录字段名）",
        "fields 的值是本项目的语义名，只能取：" + "、".join(sorted(ALLOWED_SEMANTICS)),
        "字段名（如 thing1 / time4）必须与后台模板的实际字段完全一致，否则微信会拒发。",
    ]
    for note in notes:
        print(note, file=sys.stderr)
    return 0


def _load_raw(args: argparse.Namespace) -> str:
    if args.file:
        return Path(args.file).read_text(encoding="utf-8")
    if not sys.stdin.isatty():
        piped = sys.stdin.read().strip()
        if piped:
            return piped
    return os.environ.get("PUSH_KIDS_NOTIFICATION_TEMPLATES", "")


def cmd_check(args: argparse.Namespace) -> int:
    """Validate the template map exactly as the server does, and report what each type can send."""
    raw = _load_raw(args)
    if not raw.strip():
        print("NOTIFICATION_TEMPLATES_MISSING: 没有读到配置（用 --file、管道或环境变量提供）")
        return 1
    try:
        bindings = parse_templates(raw)
    except ValueError as exc:
        print(f"NOTIFICATION_TEMPLATES_INVALID: {exc}")
        return 1

    problems: list[str] = []
    for kind in KINDS:
        binding = bindings.get(kind.type)
        if binding is None:
            print(f"- {kind.type}: 未配置 → 这类提醒会显示为「暂不可用」")
            continue
        mapped = set(binding.fields.values())
        expected = set(USED_SEMANTICS[kind.type])
        missing = sorted(expected - mapped)
        unused = sorted(mapped - expected)
        term = "长期" if binding.long_term else "一次性"
        print(f"- {kind.type}: {binding.template_id} · {term} · 字段 {len(binding.fields)} 个")
        if missing:
            print(f"    未映射的内容：{'、'.join(missing)}（这些内容不会出现在提醒里）")
        if unused:
            problems.append(f"{kind.type} 映射了这类提醒不会产生的内容：{'、'.join(unused)}")

    key = os.environ.get("PUSH_KIDS_NOTIFICATION_SECRET_KEY", "").strip()
    if not key:
        print("- secret_key: 未设置 → channel=wechat 时服务会拒绝启动")
    elif len(key) < 32:
        problems.append(f"PUSH_KIDS_NOTIFICATION_SECRET_KEY 只有 {len(key)} 个字符，至少需要 32")
    else:
        print(f"- secret_key: 已设置（{len(key)} 个字符）")

    if problems:
        for problem in problems:
            print(f"NOTIFICATION_CONFIG_PROBLEM: {problem}")
        return 1
    print(f"NOTIFICATION_TEMPLATES_VALID types={len(bindings)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="生成与校验通知通道的部署配置")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("secret", help="生成 PUSH_KIDS_NOTIFICATION_SECRET_KEY").set_defaults(
        func=cmd_secret
    )
    sub.add_parser("scaffold", help="打印 PUSH_KIDS_NOTIFICATION_TEMPLATES 骨架").set_defaults(
        func=cmd_scaffold
    )
    check = sub.add_parser("check", help="校验模板配置与密钥长度")
    check.add_argument("--file", help="模板 JSON 文件路径；缺省读管道或环境变量")
    check.set_defaults(func=cmd_check)
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
