"""Operator helper for the two notification values that cannot live in the repository.

`PUSH_KIDS_NOTIFICATION_SECRET_KEY` is generated by the deployment (it protects stored WeChat
OpenIDs), while `PUSH_KIDS_NOTIFICATION_TEMPLATES` mirrors templates approved in the WeChat console.
This tool only generates and validates those values locally; it never contacts WeChat and never
prints an existing secret.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps" / "api" / "src"))

from push_kids.notifications.domain import KINDS  # noqa: E402
from push_kids.notifications.templates import ALLOWED_SEMANTICS, parse_templates  # noqa: E402

# What each type can actually fill, best first. A console template may expose more slots than the
# product needs, and every slot it does expose must get real content or WeChat rejects the message.
AVAILABLE_SEMANTICS: dict[str, tuple[str, ...]] = {
    "member_application": ("applicant", "applied_at", "detail", "headline", "code"),
    "schedule_reminder": (
        "headline",
        "duration",
        "time",
        "notified_at",
        "countdown",
        "child",
        "detail",
    ),
    "review_digest": ("detail", "headline", "child"),
}
# The minimum a reminder has to say to be worth sending.
REQUIRED_SEMANTICS: dict[str, tuple[str, ...]] = {
    "member_application": ("applicant", "detail"),
    "schedule_reminder": ("headline", "time"),
    "review_digest": ("headline", "detail"),
}
# WeChat field types that can carry each semantic, best first. `time`/`date` fields must receive a
# timestamp, so prose semantics never go there.
SEMANTIC_FIELD_TYPES: dict[str, tuple[str, ...]] = {
    "headline": ("thing", "phrase", "const"),
    "detail": ("thing", "phrase", "const"),
    "child": ("name", "thing", "phrase"),
    "applicant": ("name", "thing", "phrase"),
    "code": ("character_string", "number", "letter"),
    "time": ("time", "date"),
    "applied_at": ("time", "date"),
    "notified_at": ("time", "date"),
    "duration": ("short_thing", "phrase", "thing"),
    "countdown": ("short_thing", "phrase", "thing"),
}
# A plausible WeChat field key per semantic, used only for the scaffold skeleton.
SAMPLE_FIELD: dict[str, str] = {
    "headline": "thing1",
    "detail": "thing2",
    "child": "name3",
    "time": "time4",
    "code": "character_string5",
    "applicant": "name6",
    "applied_at": "time7",
    "duration": "short_thing8",
    "countdown": "short_thing9",
    "notified_at": "time10",
}


def cmd_secret(_: argparse.Namespace) -> int:
    """Print one fresh key: generated here, pasted into the runtime config, never committed."""
    print(secrets.token_urlsafe(32))
    print(
        "把它填到微信云托管服务的环境变量 PUSH_KIDS_NOTIFICATION_SECRET_KEY，不要写进仓库或聊天。",
        file=sys.stderr,
    )
    print(
        "轮换这个值会让已保存的微信接收信息无法解密，家长需要重新在小程序里开启提醒。",
        file=sys.stderr,
    )
    return 0


def cmd_scaffold(_: argparse.Namespace) -> int:
    """Print a template skeleton to fill with ids and field keys from the WeChat console."""
    skeleton = {
        kind.type: {
            "template_id": f"<{kind.type}_模板ID>",
            "fields": {
                SAMPLE_FIELD[semantic]: semantic for semantic in REQUIRED_SEMANTICS[kind.type]
            },
            "long_term": False,
        }
        for kind in KINDS
    }
    print(json.dumps(skeleton, ensure_ascii=False, indent=2))
    notes = [
        "",
        "模板 ID 与 fields 的键来自微信公众平台后台：",
        "  https://mp.weixin.qq.com/ → 功能 → 订阅消息 → 公共模板库（选用）",
        "  再进入「我的模板」，展开模板即可看到模板 ID 与 {{thing1.DATA}} 这类字段名",
        "也可以用服务端接口精确导出，再用 from-wechat 子命令转换：",
        "  GET https://api.weixin.qq.com/wxaapi/newtmpl/gettemplate?access_token=ACCESS_TOKEN",
        "  文档 https://developers.weixin.qq.com/miniprogram/dev/server/API/"
        "mp-message-management/subscribe-message/api_getwxapubnewtemplate.html",
        "fields 的值是本项目的语义名，只能取：" + "、".join(sorted(ALLOWED_SEMANTICS)),
        "骨架只给出每类提醒必须说清的内容；后台模板多出来的槽位也要映射，否则微信会整条拒发。",
        "字段名（如 thing1 / time4）必须与后台模板的实际字段完全一致，否则微信会拒发。",
    ]
    for note in notes:
        print(note, file=sys.stderr)
    return 0


FIELD_TOKEN = re.compile(r"([^\n{}]*)\{\{\s*([A-Za-z_]+[0-9]*)\.DATA\s*\}\}")
# The console prints a human label in front of every slot, and that label is the only reliable way
# to tell `开始时间` from `时间`. Rules are applied in this order, so the specific ones win.
LABEL_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("距离开始", ("countdown",)),
    ("开始时间", ("time",)),
    ("申请时间", ("applied_at",)),
    ("提交时间", ("applied_at",)),
    ("提醒时间", ("notified_at",)),
    ("发送时间", ("notified_at",)),
    ("时长", ("duration",)),
    ("姓名", ("applicant", "child")),
    ("孩子", ("child",)),
    ("内容", ("detail",)),
    ("说明", ("detail",)),
    ("提示", ("detail",)),
    ("备注", ("detail",)),
    # Generic last: a plain `时间` slot is the start time unless the start time already has one.
    ("时间", ("time", "notified_at")),
)


def _field_labels(content: str) -> list[tuple[str, str]]:
    """Read `(field_key, label)` pairs in template order, e.g. `("time15", "开始时间")`."""
    seen: list[tuple[str, str]] = []
    for label, key in FIELD_TOKEN.findall(content or ""):
        if any(key == item[0] for item in seen):
            continue
        seen.append((key, label.strip().strip(":：").strip()))
    return seen


def _field_keys(content: str) -> list[str]:
    return [key for key, _ in _field_labels(content)]


def _guess_fields(kind_type: str, fields: list[tuple[str, str]]) -> dict[str, str]:
    """Propose a field→semantic map; the operator still verifies it against the console.

    Every slot is filled if the type has content that fits it, because a slot left empty makes
    WeChat reject the whole message rather than send a partial card.
    """
    available = AVAILABLE_SEMANTICS[kind_type]
    taken: dict[str, str] = {}
    used: set[str] = set()

    def claim(key: str, candidates: tuple[str, ...]) -> None:
        field_type = key.rstrip("0123456789")
        for semantic in candidates:
            if semantic in used or semantic not in available:
                continue
            if field_type not in SEMANTIC_FIELD_TYPES[semantic]:
                continue
            taken[key] = semantic
            used.add(semantic)
            return

    for keyword, candidates in LABEL_RULES:
        for key, label in fields:
            if key not in taken and keyword in label:
                claim(key, candidates)
    # Whatever the labels did not resolve falls back to the field type and the product's priority.
    for key, _ in fields:
        if key not in taken:
            claim(key, available)
    return {key: taken[key] for key, _ in fields if key in taken}


def _wechat_templates(raw: str) -> list[dict[str, object]]:
    payload = json.loads(raw)
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if not isinstance(payload, dict):
        raise ValueError("需要 gettemplate 返回的 JSON 对象")
    if payload.get("errcode") not in (None, 0):
        raise ValueError(f"微信返回错误 errcode={payload.get('errcode')} {payload.get('errmsg')}")
    data = payload.get("data")
    if not isinstance(data, list):
        raise ValueError("返回里没有 data 数组")
    return [item for item in data if isinstance(item, dict)]


def cmd_from_wechat(args: argparse.Namespace) -> int:
    """Turn a `/wxaapi/newtmpl/gettemplate` response into the env value (offline, no network)."""
    raw = Path(args.file).read_text(encoding="utf-8") if args.file else sys.stdin.read()
    try:
        templates = _wechat_templates(raw)
    except (ValueError, json.JSONDecodeError) as exc:
        print(f"WECHAT_TEMPLATE_LIST_INVALID: {exc}")
        return 1
    by_id = {str(item.get("priTmplId", "")): item for item in templates}

    assignments: dict[str, str] = {}
    for pair in args.map or []:
        kind_type, _, template_id = pair.partition("=")
        if kind_type not in AVAILABLE_SEMANTICS or not template_id:
            print(f"WECHAT_TEMPLATE_MAP_INVALID: {pair}（格式为 通知类型=模板ID）")
            return 1
        assignments[kind_type] = template_id

    if not assignments:
        print(f"WECHAT_TEMPLATE_LIST count={len(templates)}")
        for item in templates:
            keys = _field_keys(str(item.get("content", "")))
            term = "长期" if item.get("type") == 3 else "一次性"
            print(f"- {item.get('priTmplId')} · {term} · {item.get('title')}")
            print(f"    字段：{'、'.join(keys) or '（未解析到字段）'}")
        print("", file=sys.stderr)
        print(
            "再选定归属即可产出配置，例如："
            "--map schedule_reminder=<模板ID> --map review_digest=<模板ID>",
            file=sys.stderr,
        )
        return 0

    result: dict[str, object] = {}
    for kind in KINDS:
        template_id = assignments.get(kind.type)
        if template_id is None:
            continue
        item = by_id.get(template_id)
        if item is None:
            print(f"WECHAT_TEMPLATE_NOT_FOUND: {kind.type} 找不到模板 {template_id}")
            return 1
        labelled = _field_labels(str(item.get("content", "")))
        keys = [key for key, _ in labelled]
        fields = _guess_fields(kind.type, labelled)
        entry: dict[str, object] = {"template_id": template_id, "fields": fields}
        if item.get("type") == 3:
            entry["long_term"] = True
        result[kind.type] = entry
        unmapped = [key for key in keys if key not in fields]
        if unmapped:
            print(
                f"{kind.type}: 模板字段 {'、'.join(unmapped)} 没有对应内容，"
                "微信会按参数缺失拒发（47003），请换字段更贴合的模板",
                file=sys.stderr,
            )
        absent = [item for item in REQUIRED_SEMANTICS[kind.type] if item not in fields.values()]
        if absent:
            print(
                f"{kind.type}: 这个模板放不下 {'、'.join(absent)}，提醒会缺少关键信息",
                file=sys.stderr,
            )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    print("", file=sys.stderr)
    print("fields 的映射是按字段名推测的，请对照后台模板详情确认后再上线。", file=sys.stderr)
    print("enum_string 只能取枚举值，不适合本项目的自由文本内容。", file=sys.stderr)
    return 0


def _load_raw(args: argparse.Namespace) -> str:
    if args.file:
        return Path(args.file).read_text(encoding="utf-8")
    if not sys.stdin.isatty():
        piped = sys.stdin.read().strip()
        if piped:
            return piped
    return os.environ.get("PUSH_KIDS_NOTIFICATION_TEMPLATES", "")


def cmd_check(args: argparse.Namespace) -> int:
    """Validate the template map exactly as the server does, and report what each type can send."""
    raw = _load_raw(args)
    if not raw.strip():
        print("NOTIFICATION_TEMPLATES_MISSING: 没有读到配置（用 --file、管道或环境变量提供）")
        return 1
    try:
        bindings = parse_templates(raw)
    except ValueError as exc:
        print(f"NOTIFICATION_TEMPLATES_INVALID: {exc}")
        return 1

    problems: list[str] = []
    for kind in KINDS:
        binding = bindings.get(kind.type)
        if binding is None:
            print(f"- {kind.type}: 未配置 → 这类提醒会显示为「暂不可用」")
            continue
        mapped = set(binding.fields.values())
        available = set(AVAILABLE_SEMANTICS[kind.type])
        required = set(REQUIRED_SEMANTICS[kind.type])
        term = "长期" if binding.long_term else "一次性"
        print(f"- {kind.type}: {binding.template_id} · {term} · 字段 {len(binding.fields)} 个")
        unfillable = sorted(mapped - available)
        if unfillable:
            # 这类槽位在运行时会被记成 template_field_missing 并整条跳过。
            problems.append(
                f"{kind.type} 映射了这类提醒不会产生的内容：{'、'.join(unfillable)}"
                "（微信会整条拒发，服务会跳过并记录 template_field_missing）"
            )
        absent = sorted(required - mapped)
        if absent:
            problems.append(f"{kind.type} 缺少必须说清的内容：{'、'.join(absent)}")
        optional = sorted(available - mapped - required)
        if optional:
            print(f"    模板没有这些槽位，将不会出现：{'、'.join(optional)}")

    key = os.environ.get("PUSH_KIDS_NOTIFICATION_SECRET_KEY", "").strip()
    if not key:
        print("- secret_key: 未设置 → channel=wechat 时服务会拒绝启动")
    elif len(key) < 32:
        problems.append(f"PUSH_KIDS_NOTIFICATION_SECRET_KEY 只有 {len(key)} 个字符，至少需要 32")
    else:
        print(f"- secret_key: 已设置（{len(key)} 个字符）")

    if problems:
        for problem in problems:
            print(f"NOTIFICATION_CONFIG_PROBLEM: {problem}")
        return 1
    print(f"NOTIFICATION_TEMPLATES_VALID types={len(bindings)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="生成与校验通知通道的部署配置")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("secret", help="生成 PUSH_KIDS_NOTIFICATION_SECRET_KEY").set_defaults(
        func=cmd_secret
    )
    sub.add_parser("scaffold", help="打印 PUSH_KIDS_NOTIFICATION_TEMPLATES 骨架").set_defaults(
        func=cmd_scaffold
    )
    check = sub.add_parser("check", help="校验模板配置与密钥长度")
    check.add_argument("--file", help="模板 JSON 文件路径；缺省读管道或环境变量")
    check.set_defaults(func=cmd_check)
    from_wechat = sub.add_parser(
        "from-wechat",
        help="把 /wxaapi/newtmpl/gettemplate 的返回转成 PUSH_KIDS_NOTIFICATION_TEMPLATES",
    )
    from_wechat.add_argument("--file", help="gettemplate 返回的 JSON 文件；缺省读标准输入")
    from_wechat.add_argument(
        "--map",
        action="append",
        metavar="类型=模板ID",
        help="指定通知类型使用哪个模板，可重复；不给则只列出后台已有模板",
    )
    from_wechat.set_defaults(func=cmd_from_wechat)
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
